### ISSUE TITLE
[Meeting] [2024/03/07] Meeting Log

### ISSUE THREAD

**Issue by suhyenim** [hi-sujung/hisujung-msa-k8s#1]
## 🔎 회의 안건
- [x] 프로젝트 주제 설정
- [x] Github Organization, Repository 생성
- [x] 서기 순서, 정기 회의 일정

## 📚 내용 정리
- 프로젝트 주제
  - 기존 프로젝트: 게시판, 해시태그에코, cabinet, 하이수정이
  - 새로운 프로젝트: cctv, pr+gpt
  - 최종: ~cabinet~ 하이수정이
- Github Organization: ~```cabinet-cloudcomputing```~ ```hi-sujung```
- 서기 순서: 혜지-수현-은재-정은
- 온라인 정기 회의: 매주 금요일 20시

## 💭 ToDo
- 회의 기록은 정리하여 Github Project에 업로드
- 에러, 지식은 Github issue에 문서화
- PR, ISSUE, COMMIT 규칙 정리
- Q. 오픈소스 프로젝트를 이어서 진행해도 괜찮은가? &rarr; 괜찮음
- (2024.03.12) 팀원 추가모집, 주제 재설정

**Comment by suhyenim** [comment]
깔끔한 정리 좋아요 !
