### ISSUE TITLE
[Meeting] [2024/05/28] Meeting Log

### ISSUE THREAD

**Issue by suhyenim** [hi-sujung/hisujung-msa-k8s#11]
## 🔎 회의 안건
- [x] Redis를 하나의 MS로 구현 여부 질문 
- [x]  각 MS의 Service 타입 논의
- [x]  프로그램 채점 방식 질문

## 📚 내용 정리
- Redis를 하나의 MS로 구현 필요
   - 기존 백엔드 서비스와 별개로, DB 서비스를 하나로 구현해야 함
- 각 MS의 Service 타입
   - 클라이언트와 통신하는 front - LoadBalancer
   - 이외의 MS 간 통신하는 MS들 - ClusterIP
   - 각 MS의 Service를 통해 통신하는 구조 (하나의 MS는 하나의 Service)
 - Auto-scaling 구현 시, 부하 시나리오 필요
 - 프로그램 테스트(채점) 방식
   - 제출한 yml 파일을 교수님 클러스터에 띄우고, 가이드대로 잘 동작하는지 확인

## 💭 ToDo
- GKE 배포 후 MS간 연동되는지 확인
