### ISSUE TITLE
[Meeting] [2024/03/19] Meeting Log

### ISSUE THREAD

**Issue by suhyenim** [hi-sujung/hisujung-msa-k8s#2]
## 🔎 회의 안건
- [x]  비대면 정기 회의 일정
- [x]  Meetign Note 서기 순서 결정
- [x]  마이크로서비스 분리에 따른 역할 분담

## 📚 내용 정리
- 기존 프로젝트: `하이수정`
- 서기 순서: 혜지 - 유진 - 민지 - 수현 - 은재 - 정은 - 혜림
- 온라인 정기 회의: 🗓️ 매주 목요일 오후 11시 (discord로 진행)
- 프로젝트 계획서 제출 내용
   - 1) 개요: 구축하려는 서비스에 대한 소개, 기대 사용자와 기대 효과, 타 서비스와의 차별점
   - 2) 향후 개발 계획: 개발 관련 계획 (협업 방법, 개발 도구 등), 향후 일정, 팀원별 업무 분담 계획
- 각 마이크로서비스별 팀원 역할 분담
   - 공지사항(교내/대외, 추천시스템): `부팀장` 혜지, 민지, 유진
   - 사용자 관리: `부팀장` 정은, 수현
   - 포트폴리오: `부팀장` 유진, 은재, 혜림

## 💭 ToDo
- 마이크로서비스 분리
   - 마이크로서비스 별 레포지토리 구축
   - 마이크로서비스별 데이터베이스 구축
   - 마이크로서비스 분리를 위한 프로젝트 코드 리팩토링
- 크롤링한 데이터 저장 및 크롤링 자동화 공부: 혜지
- (2024.03.26) 교수님 미팅

**Comment by imsuhyen** [comment]
깔끔할 정리 감사합니다😀

**Comment by suhyenim** [comment]
깔끔할 정리 감사합니다😀
