### ISSUE TITLE
[Meeting] [2024/03/29] Meeting Log

### ISSUE THREAD

**Issue by suhyenim** [hi-sujung/hisujung-msa-k8s#4]
## 🔎 회의 안건
- [x] msa 변경에 따른 역할 분담
- [x] 중간 발표까지의 계획 수립
- [x] 신규 기능 토의

## 📚 내용 정리
- 4개의 마이크로서비스로 구성 : `공지사항`, `공지사항 추천시스템`, `사용자 관리`, `포트폴리오`
   - `공지사항` : 민지, 유진, 수현 
   - `공지사항 추천시스템` : 혜지
   - `사용자 관리` : 정은, 수현
   - `포트폴리오` : 유진, 은재, 혜림
- 포트폴리오 신규 기능 추가
   - 참여한 공지사항을 기반으로 GPT API를 활용하여 포트폴리오를 자동으로 생성해주는 기능
- issue, pr, meeting note 템플릿 제작
   - `hi-sujung` 레포지토리 내 마크다운 파일 참고

## 💭 ToDo
- 다음 회의 전까지 모두 5주차 강의까지 완료
- 레포지토리 분리 : 유진, 은재
- 크롤링 자동화 공부 : 혜지
- GPT API 관련 기능 추가 : 유진
- msa 전환 과정에서 프론트엔드 구성 질문 : 수현
   - 교수님께 이메일 전송
- (2024.04.01) 다음주 월요일 추가 회의 진행

**Comment by rlawjd10** [comment]
정리 감사합니다. 3팀 파이팅입니다~~!!!
