### ISSUE TITLE
[Meeting] [2024/04/01] Meeting Log

### ISSUE THREAD

**Issue by EunjaeJo** [hi-sujung/hisujung-msa-k8s#5]
## 🔎 회의 안건
- [x] 기존 프로젝트 repository를 MSA에 맞게 분할
- [x]  MS팀별 구현 계획 수립
- [x] 서비스 간 직접 메시징/간접 메시징 의논

## 📚 내용 정리
- 각 micro service 별 팀장 선발
   - `공지사항` : 혜지
   - `사용자 관리` : 정은
   - `포트폴리오` : 유진
- 프론트엔드 repository 
   - 기존 repository 사용
- 서비스 간 통신
   - 각 서비스 일정 수준 이상 구현 이후 직접 메시징/간접 메시징 방법 선택 및 구현

## 💭 ToDo
**MS팀별 구현 계획**
- `공지사항`
    - DB 구축
        - 크롤링: 혜지 
     - 기능 개선
        - 검색 기능: 민지
        - 좋아요 기능(참여 여부 선택 기능 추가): 민지
        - 공지사항과 포트폴리오 간 데이터 통신: 유진
    - 추천 시스템
        - nginx uwsgi 사용하여 서버에 업로드: 유진 
- `사용자 관리`
   - DB 구축(Redis 활용) 및 서버 업로드: 수현
   - 사용자 관리 - 데이터 통신, 사용자 관리 - 공지사항 데이터 통신: 정은
   - 로그아웃: 유진
- `포트폴리오`
   - ERD 구현 및 DB 구축: 혜림
   - 참여 공지사항 목록 구축 및 포트폴리오 - 사용자 관리 데이터 통신: 은재
   - 참여 공지사항 기반 포트폴리오 자동 생성, 포트폴리오 - 공지사항 데이터 통신: 유진 
- (2024.04.10) 다음주 수요일 회의 진행

**Comment by rlawjd10** [comment]
팀별 구현 계획이 어느정도 구체적으로 세웠으니 앞으로 발전할 일만 남았습니다~~
은재님 정리 감사해요~~^^ 모두 파이팅입니다~!
